--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImperaZim/FakePlayer
build-by-default: true
branches:
- main
projects:
  FakePlayer:
    icon: meta/1655767389117.png
    lint:
      phpstan: false 
    path: ""
...
